---
- name: install dhcp-server
  apt: 
   name: isc-dhcp-server
   state: present

- name: dhcp interfaces config
  template:
   src: isc-dchp-server.j2
   dest: /etc/default/isc-dchp-server

- name: dhcp leases config
  template:
   src: dhcpd.conf.j2
   dest: /etc/dhcp/dhcpd.conf

- name: log config
  template: 
   src: dhcpd.log.conf.j2
   dest: /etc/rsyslog.d/dhcpd.conf

- name: log restart
  service: 
   name: rsyslog
   state: restarted
   
- name: dhcp restart
  service: 
   name: isc-dhcp-server
   state: restarted