- name: install pxe packages
  apt:
  pkg: "{{pxe}}"
  state: present

- name: download net_installer debian
  get_url: https://deb.debian.org/debian/dists/bullseye/main/installer-amd64/current/images/netboot/netboot.tar.gz
  dest: /srv/tftp/

- name: unzip net_installer
  command: 
    cmd: cd /srv/tftp/ && tar xfz netboot.tar.gz

- name: pxe config
  command:
    cmd: ln -s /srv/tftp/debian-installer/amd64/bootnetx64.efi /srv/tftp/
  template:
    scr: txt.cfg.j2
    dest: /srv/tftp/debian-installer/amd64/boot-screens/txt.cfg

- name: preseed.conf
  template:
    scr: preseed.cfg.j2
    dest: /srv/tftp/preseed.cfg

- name: restart services
  service:
    name: tftpd-hpa
    state: started



